In [ ]:
# pip install statsmodels

In [19]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

In [26]:
word_df = pd.read_csv("webpage/data_for_plotting.csv")
word_cleaned = word_df.dropna(axis='columns', how='all')
word_cleaned

,Review_ID,Rating,Reviewer_Location,Review_Text,Branch,Year,Month,is_good_review,review_clean,neg,...,word_money,word_hour,word_disappointed,word_great,word_close,word_love,word_poor,word_pay,word_people,word_waste
0,670772142,4,Australia,If you've ever been to Disneyland anywhere you...,Disneyland_HongKong,2019,4,1,ever disneyland anywhere find disneyland hong ...,0.000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0
1,670682799,4,Philippines,Its been a while since d last time we visit HK...,Disneyland_HongKong,2019,5,1,since last time visit hk disneyland yet time s...,0.040,...,0.000000,0.000000,0.0,0.085604,0.000000,0.000000,0.0,0.000000,0.000000,0.0
2,670623270,4,United Arab Emirates,Thanks God it wasn t too hot or too humid wh...,Disneyland_HongKong,2019,4,1,thanks god hot humid visit park otherwise woul...,0.024,...,0.000000,0.071062,0.0,0.057092,0.075894,0.000000,0.0,0.000000,0.000000,0.0
3,670607911,4,Australia,HK Disneyland is a great compact park. Unfortu...,Disneyland_HongKong,2019,4,1,hk disneyland great compact park unfortunately...,0.080,...,0.000000,0.000000,0.0,0.077392,0.102879,0.085448,0.0,0.125551,0.000000,0.0
4,670607296,4,United Kingdom,"the location is not in the city, took around 1...",Disneyland_HongKong,2019,4,1,location city take around hour kowlon kid like...,0.000,...,0.000000,0.193089,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40038,92198076,4,United Kingdom,Although our pick up was prompt the taxi drive...,Disneyland_Paris,2011,1,1,although pick prompt taxi driver wasnt sure ti...,0.096,...,0.000000,0.037606,0.0,0.000000,0.040163,0.000000,0.0,0.000000,0.036929,0.0
40039,92061774,4,Germany,Just returned from a 4 days family trip to Dis...,Disneyland_Paris,2011,1,1,return day family trip disneyland two boy age ...,0.028,...,0.034320,0.136121,0.0,0.065616,0.058150,0.000000,0.0,0.000000,0.080202,0.0
40040,91995748,1,United Kingdom,We spent the 20 Dec 2010 in the Disney park an...,Disneyland_Paris,2010,12,0,spent dec disney park lunchtime attraction sta...,0.067,...,0.040103,0.031811,0.0,0.000000,0.169872,0.000000,0.0,0.041461,0.124954,0.0
40041,91984642,2,United Kingdom,Well I was really looking forward to this trip...,Disneyland_Paris,2010,12,0,well really look forward trip christmas period...,0.067,...,0.000000,0.037974,0.0,0.030508,0.000000,0.000000,0.0,0.000000,0.000000,0.0
40042,91827418,5,United Kingdom,If staying at a Disney hotel make good use of ...,Disneyland_Paris,2010,9,1,stay disney hotel make good use extra hour fas...,0.041,...,0.000000,0.166341,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0

In [27]:
word_working = word_cleaned.dropna()
word_working

,Review_ID,Rating,Reviewer_Location,Review_Text,Branch,Year,Month,is_good_review,review_clean,neg,...,word_money,word_hour,word_disappointed,word_great,word_close,word_love,word_poor,word_pay,word_people,word_waste
0,670772142,4,Australia,If you've ever been to Disneyland anywhere you...,Disneyland_HongKong,2019,4,1,ever disneyland anywhere find disneyland hong ...,0.000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0
1,670682799,4,Philippines,Its been a while since d last time we visit HK...,Disneyland_HongKong,2019,5,1,since last time visit hk disneyland yet time s...,0.040,...,0.000000,0.000000,0.0,0.085604,0.000000,0.000000,0.0,0.000000,0.000000,0.0
2,670623270,4,United Arab Emirates,Thanks God it wasn t too hot or too humid wh...,Disneyland_HongKong,2019,4,1,thanks god hot humid visit park otherwise woul...,0.024,...,0.000000,0.071062,0.0,0.057092,0.075894,0.000000,0.0,0.000000,0.000000,0.0
3,670607911,4,Australia,HK Disneyland is a great compact park. Unfortu...,Disneyland_HongKong,2019,4,1,hk disneyland great compact park unfortunately...,0.080,...,0.000000,0.000000,0.0,0.077392,0.102879,0.085448,0.0,0.125551,0.000000,0.0
4,670607296,4,United Kingdom,"the location is not in the city, took around 1...",Disneyland_HongKong,2019,4,1,location city take around hour kowlon kid like...,0.000,...,0.000000,0.193089,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40038,92198076,4,United Kingdom,Although our pick up was prompt the taxi drive...,Disneyland_Paris,2011,1,1,although pick prompt taxi driver wasnt sure ti...,0.096,...,0.000000,0.037606,0.0,0.000000,0.040163,0.000000,0.0,0.000000,0.036929,0.0
40039,92061774,4,Germany,Just returned from a 4 days family trip to Dis...,Disneyland_Paris,2011,1,1,return day family trip disneyland two boy age ...,0.028,...,0.034320,0.136121,0.0,0.065616,0.058150,0.000000,0.0,0.000000,0.080202,0.0
40040,91995748,1,United Kingdom,We spent the 20 Dec 2010 in the Disney park an...,Disneyland_Paris,2010,12,0,spent dec disney park lunchtime attraction sta...,0.067,...,0.040103,0.031811,0.0,0.000000,0.169872,0.000000,0.0,0.041461,0.124954,0.0
40041,91984642,2,United Kingdom,Well I was really looking forward to this trip...,Disneyland_Paris,2010,12,0,well really look forward trip christmas period...,0.067,...,0.000000,0.037974,0.0,0.030508,0.000000,0.000000,0.0,0.000000,0.000000,0.0
40042,91827418,5,United Kingdom,If staying at a Disney hotel make good use of ...,Disneyland_Paris,2010,9,1,stay disney hotel make good use extra hour fas...,0.041,...,0.000000,0.166341,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0

In [30]:
label = "is_good_review"
ignore_cols = [label, "Review_Text", "review_clean", "Reviewer_Location","Branch","Rating", ""]
all_predictors = [c for c in word_working.columns if c not in ignore_cols]
all_predictors

['Review_ID',
 'Year',
 'Month',
 'neg',
 'pos',
 'neu',
 'compound',
 'characters',
 'words',
 'word_money',
 'word_hour',
 'word_disappointed',
 'word_great',
 'word_close',
 'word_love',
 'word_poor',
 'word_pay',
 'word_people',
 'word_waste']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(reviews_df[all_predictors], reviews_df["is_good_review"], test_size = 0.20, random_state = 42)
X_train

In [ ]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
from sklearn.feature_selection import RFE
rfe = RFE(logreg, 15)             
rfe = rfe.fit(X_train, y_train)

In [ ]:
metrics.accuracy_score(y_pred_final['Converted'], y_pred_final.final_predicted)

TP = confusion2[1,1]
TN = confusion2[0,0] 
FP = confusion2[0,1] 
FN = confusion2[1,0] 

TP/(TP+FP)
TP/(TP+FN)